### ISSUE TITLE
Load a config file on startup

### ISSUE THREAD

**Issue by mazlo** [igorlogius/automate-click#1]
Nice plugin, thank you. It works!

I was wondering if you persist the configuration of all codes, delays, and urls somewhere in a folder (firefox profile?!), so that a config file (your example config file, e.g.) could be loaded on startup of the firefox browser. 

Thank you.

**Comment by igorlogius** [comment]
I am not 100% certain ... i'll have to check, 
but if i had to guess, i dont thing local file access  on statrup doesn not seem like a good idea. 

But i'll check. 
Later. 

(And sorry for the late reply)

**Comment by igorlogius** [comment]
I think, i'll have to reject the proposal (for now)l, because i think using absolute filepaths would be to much of potential security risk/issue. (And would not go well with multiuser systems)
Anybody could place any "startup" config files into  /tmp and this would trigger/cause unwanted click actions on websites.

If i find a way via the web-ext api to get the relativ location of the started firefox profile folder (or some other usable directory)  i might reconsider, but for now i can only  propose to  you to create a custom fork which contains the change absolute path solution if you really want it.

But i would not want to add it to the main development trunk.  Sorry.
