### ISSUE TITLE
[Feature Request] stop the repeating click execution after a certain number / time

### ISSUE THREAD

**Issue by igorlogius** [igorlogius/automate-click#18]
**Is your feature request related to a problem? Please describe.**

A user would like to terminate the repeating click execution after a certain number of executions  and / or  a certain time (limit) 

**Describe the solution you'd like**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

![ksnip_20220224-191156](https://user-images.githubusercontent.com/67047467/155582740-5e9edd2a-8d8e-4da8-a84f-378d618bc17a.png)

**Comment by dreamflow** [comment]
hi , i'd be happy about both features being added : Max Repeats , Max Timeout .
it would be very helpfull for my usecase , there automate-click does automatically
click the login-button on the login-site of my web-email-account . this works fine .

problem is when i log out of my web-email-account , the site jumps back to
the login-site with the same url , that i've configured automate-click to auto-
matically click the login-button .
the result is , that after i log out , automate-click logs me in again automatically ,
so that in the end it's not possible to log out .

the features Max Repeats , Max Timeout would very probably solve this problem .

**Comment by igorlogius** [comment]
> problem is when i log out of my web-email-account , the site jumps back to the login-site with the same url 

@dreamflow 
If you get  redirected to the login page (meanting that the logout triggers a page naviagtion)  than neither Max Repeats or Timeout would work, since the page navigation  will  just re-start  the automation.

This is kind of a limitation  since the repeated click action is triggered from within a content-script (which gets injected after each a page has been loaded)

**Comment by igorlogius** [comment]
Max Repeats  added in  `1.9.3`

Note: 
 -  has no effects if no repeatdelay is  not set to a value > 0 

I am gone skip the Time based stop mechanic since the requester only seemed to ask for one solution ... and i am a lazy. :)

**Comment by dreamflow** [comment]
@igorlogius

thank you for the details of the
inner workings of automate-click .

now automate-click turns out to be even more genius
for my use case , because my web-email-account
logs out automatically after some hours . but since then
also a page-redirect happens back to the login-page ,
automate-click would automatically login again .

for the more seldom cases , where i want to log out
from my web-email-account , i simply can before
turn off automate-click .

thank you for automate-click , it's a very helpful tool .
