### ISSUE TITLE
Option to enforce the same tab

### ISSUE THREAD

**Issue by khabib227** [igorlogius/automate-click#26]
Please think in add a option, per rule, to enforce the clicked link open in the same tab. Thanks!

**Comment by igorlogius** [comment]
Sorry, but this request seem out-of-scope.

Since the link action and effect would need to be very tightly coupled and specialized to underlying element. 

You should be able to use a userscript manager like (greasymonkey) for something like this. 
It should allow you to extract anchor href's to initalize a tab navigation.

Hope this info helps.
