### ISSUE TITLE
#print not working

### ISSUE THREAD

**Issue by d762** [igorlogius/automate-click#4]
So i tried CSS selector #print in Firefox PDF Viewer and it did not work...

**Comment by igorlogius** [comment]
Oh, the Firefox PDF Viewer ... might be special case. 
The most likely reason i can think of without checking would be that the content-script might not be injectable 
either because the pdf view is protected or simply not capable of receiving it. 

I'll look into it and try it find out if it is at all possible or not.

**Comment by igorlogius** [comment]
A quick test confirms what i though, the required content-script does not seem to get injected into the PDF Viewer page.
And sadly i could not find any hint on how this could be done, in the web-ext documentation. 

I'll keep looking a bit longer and see if i can find a workaround or a absolute statement from mozilla that this is intented not doable. Later.

**Comment by d762** [comment]
i think it isnt possible. I solved my problem with pdf2printer wrap of
Pdfxcviewer

On Wednesday, 7 July 2021, igorlogius ***@***.***> wrote:
> Oh, the Firefox PDF Viewer ... might be special case.
> The most likely reason i can think of without checking would be that the
content-script might not be injectable
> either because the pdf view is protected or simply not capable of
receiving it.
>
> I'll look into it and try it find out if it is at all possible or not.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/-ydMm3erRSQ6CSSltx15MjZPNBHc2GNkLIcD-tsOaCckkJKwpuLdg-wKAMrEopJe7hakObjSKUpbXnBuBKjZWGE00LkDYLZeBsgBbY_EEG551VO841D-pGBCKZdiA7cme8mGGEP6n5QCS4Ox4QFqZy8U6zqcOrvxlqFbq-0FAXEIIvReau3UaMaE_9nGG59MsnbQ8M022r73BcXeXv1h08wJIQT78o3kp7fzjAkZqw=s0-d-e1-ft#https://github.com/notifications/beacon/AOOILKDQAJMEWT5LJ2RHIE3TWREKLA5CNFSM47SQWF22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGQYDIRA.gif>

**Comment by igorlogius** [comment]
Good that you found a solution that works for you. 
I asked  some other addons devs and it seems that chrome allows injection of content scripts into its pdf viewer, but firefox doesnt. 
Just as you stated, i/we think that this is intentional. 
When manifest version 3 is released i can recheck if something changed, but for now i'll be closing this issue with label: wont fix.
Not because i dont want to , but because i sadly. cant.
