### ISSUE TITLE
Are search terms supported?

### ISSUE THREAD

**Issue by AfromD** [igorlogius/automate-click#44]
**Describe the bug**
I am trying to specify a css element by a search term in a property like this
div[aria-label*="next"]

**To Reproduce**
I have entered div[aria-label*="next"] as the css selector. 
I have entered the url as a regex
I have set intital delay to 5 seconds
I have set repeat to three seconds

The web page is dynamically generated with css id's that are changing, so I have to go by the attribute to identify the right element. The required css element is not always visible on first load, but can be part of the web page after interaction.
The click on the element triggers java script with a click event and the coordinates of the click, so that the application knows which element is clicked

**Expected behavior**
the next button behaves as clicked

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 112

**Additional context**
complete css element:
`<div style="transform: translate3d(0px, 0px, 0px); z-index: 20; display: block; left: 1484px; top: 1048px; width: 71px; height: 66px; visibility: visible; outline-style: none;" id="si244501" class="cp-frameset" tabindex="2500" role="button" aria-label="   Trigger this button to go to the next slide"></div>`

mousedown code:
```function(a) {
  if (void 0 != a && !cp.disableInteractions) {
    var g = a.type.toLowerCase(),
      i = 0 != e.canvasObj.ss || e.is_inside_canvas(a);
    if ("mousemove" != g) e.clicked = "mousedown" == a.type.toLowerCase();
    else {
      if (e.clicked || s.x == a.clientX && s.y == a.clientY) return;
      s.x = a.clientX;
      s.y = a.clientY
    }
    if (("mousemove" == a.type.toLowerCase() ||
        "mousedown" == a.type.toLowerCase() || "mouseover" == a.type.toLowerCase() || "touch" == a.type.toLowerCase() || "touchstart" == a.type.toLowerCase()) && !i) d && (cp.device == cp.DESKTOP && "mousemove" == a.type.toLowerCase()) && d(c, i, a);
    else if (g = e, e.cloneOfBaseStateItem && (g = cp.getDisplayObjByCP_UID(e.baseStateItemID)), !g || !(g.parentData && void 0 != g.parentData.enabled) || g.parentData.enabled) f && f(), d && d(c, i, a)
  }
}```

**Comment by igorlogius** [comment]
Hello @AfromD 

first of, thank you for taking the time to create this bug report. 


Next up, i'll answer your general title question. Yes search terms like 
`div[aria-label*="next"]` should AFAIK work. To be more precise, 
everything that is valid for `document.querySelectorAll` [ref.](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) should work, since the string is directly passed to it. 

So at the moment with the information you provided i would suspect that the issue is not related to the selector. 

For debugging i'd suggest the following steps. 

First check in the development console if you can trigger the click like this: `Array.from(document.querySelectorAll('div[aria-label*="next"]')).forEach(e => { if(typeof e.click === 'function'){ e.click();}});` manually. 

If that works as expected, i would next try to increase the delay to a very high number and to make sure that the issue is not related to an `not ready` page state. 

Please try these steps and let me know your results.
