### ISSUE TITLE
Support clicking reoccuring items

### ISSUE THREAD

**Issue by greaka** [igorlogius/automate-click#5]
Hey there,

I have a few sites that require clicks periodically and wanted to ask if you would be interested in adding an option to have the extension periodically check for things to click?

**Comment by igorlogius** [comment]
@greaka 

I would have 2 suggestion

1) lets call it "repeat"  (reaccuring sounds a little off, or is it just me?) 
2) and instead of a boolean lets make it its own number value ( >=0, milliseconds) 
  * value 0 (default), means   no repetition 
  * value > 0,  will repeat the click action in the given amount of milliseconds 

I think that this would make more sense than reusing the delay value for the repetition 
or what do you think?

**Comment by igorlogius** [comment]
@greaka 

That looks good.
