### ISSUE TITLE
[Recommend] Dark Theme, Sort, Reorder Options

### ISSUE THREAD

**Issue by gesdemirei** [igorlogius/automate-click#9]
I use dark theme on browser. When I open extension's Options page, page's background disturbs me because of it is white. Also it doesn't allow to sort and to reorder strings. If you would add these features on next update, it would be to have more features.

**Comment by igorlogius** [comment]
Hi, thanks for the 3 suggestions.

1. dark theme:  since style is a bit of a personal preference, i dont want to invest to much time into it, since i am sure i can not please everyone. That is why i opted to use a "grey" background for the extension page  and so i dont quite understand what you mean with "white". Perhaps you are using an older version or  do you  mean the background of the input fields?  

2. sort + reorder : Yeah, that sounds like a good idea, i only have to think about how i'll implement this. You can expect it to be added.

**Comment by igorlogius** [comment]
see  ref #10
